[package]
name = "backroll-transport-udp"
version = "0.1.0"
edition = "2018"
authors = ["Hourai Teahouse Developers <contact@houraiteahouse.net>"]
description = "A raw async UDP implementation for backroll-transport."
license = "ISC"

[dependencies]
backroll_transport = { path = "../backroll_transport" }
async-channel = "1.6"
async-net = "1.6.0" 
bevy_tasks = "0.5"
tracing = "0.1"