[package]
name = "backroll_transport_udp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backroll_transport = { path = "../backroll_transport" }
async-channel = "1.6"
async-net = "1.6.0" 
bevy_tasks = "0.5"
tracing = "0.1"