[workspace]
resolver = "2" # Needed by Bevy/wgpu
members = [
  "backroll",
  "bevy_backroll",
  "backroll_transport",
  "backroll_transport_udp",
  # Intentionally left out as it breaks workspace builds
  "backroll_transport_steam",
]