[package]
name = "bevy_backroll"
version = "0.1.0"
edition = "2018"

# [package.metadata.docs.rs]
features = [ "docs-only" ]

[features]
default = []
steam = ["bevy-steamworks", "backroll_transport_steam"]
# Skip looking for the Steamworks SDK for docs builds
docs-only = ["steam", "backroll_transport_steam/docs-only"]

[dependencies]
backroll = { path = "../backroll", version = "0.1" }
bevy_ecs = "0.5"
bevy_core = "0.5"
bevy_tasks = "0.5"
bevy_app = "0.5"
tracing = "0.1"

# Optional dependencies
bevy-steamworks = { version = "0.1", optional = true }
backroll_transport_steam = { path = "../backroll_transport_steam", version = "0.1", optional = true }

[dev-dependencies]
bevy = "0.5"